---
functional:
  - Сайт должен иметь возможность создания команд для участия в турнирах
  - Сайт должен предоставлять возможность выбора языка программирования при решении задач
  - Сайт должен предоставлять возможность соревноваться двум игрокам в решении задач
  - Сайт должен иметь рейтинг игроков и возможность просмотра их статистики
  - Сайт должен предоставлять возможность игры с ботом и игры с другом по ссылке
non-functional:
  - Сайт должен иметь удобный и интуитивно понятный интерфейс для пользователей всех уровней
  - Сайт должен работать быстро и без прерываний даже при высокой нагрузке
  - Сайт должен быть легким в использовании и быстрым в работе
  - Сайт должен обеспечивать безопасность данных пользователей
  - Сайт должен быть адаптирован для использования на мобильных устройствах
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен обрабатывать большой объем трафика и быть способным работать с 1000 одновременных пользователей
implicit:
  - Сайт должен обеспечивать честность и надежность соревнований между игроками
  - Сайт должен обеспечивать равные возможности для всех игроков, без привилегий для определенных групп пользователей.
  - Сайт должен обеспечивать конфиденциальность личных данных пользователей, а также защиту от мошенничества и недобросовестных действий других пользователей
  - Сайт должен поддерживать честную и спортивную игру без использования недостоверных или запрещенных методов
